"""SQLAlchemy models for the local SQLite database.

Conventions
- Primary keys are UUID strings generated by the application (stable across sync).
- All timestamps are UTC. Session-relative offsets are milliseconds from the
  session's `started_at` on one shared timebase (captures, notes, audio, transcript).
- Review state, work status and sharing state are deliberately separate columns.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    TypeDecorator,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def new_id() -> str:
    return str(uuid.uuid4())


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class UTCDateTime(TypeDecorator):
    """Stores naive UTC, always returns aware UTC datetimes."""

    impl = DateTime
    cache_ok = True

    def process_bind_param(self, value: Optional[datetime], dialect):  # noqa: ANN001
        if value is None:
            return None
        if value.tzinfo is None:
            value = value.replace(tzinfo=timezone.utc)
        return value.astimezone(timezone.utc).replace(tzinfo=None)

    def process_result_value(self, value: Optional[datetime], dialect):  # noqa: ANN001
        if value is None:
            return None
        return value.replace(tzinfo=timezone.utc)


class Base(DeclarativeBase):
    pass


# Enumerations kept as plain strings (validated in the API layer).
REVIEW_STATES = ("pending", "approved", "dismissed")
WORK_STATUSES = ("open", "in_progress", "done", "wont_do")
SHARING_STATES = ("local_only", "pending", "synced", "failed", "conflict")
ITEM_TYPES = ("bug", "improvement", "idea", "task", "question", "note")


class Setting(Base):
    __tablename__ = "settings"
    key: Mapped[str] = mapped_column(String(100), primary_key=True)
    value: Mapped[Any] = mapped_column(JSON, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow, onupdate=utcnow)


class Project(Base):
    __tablename__ = "projects"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, default="")
    glossary: Mapped[str] = mapped_column(Text, default="")
    is_demo: Mapped[bool] = mapped_column(Boolean, default=False)
    archived: Mapped[bool] = mapped_column(Boolean, default=False)
    # Sharing: a project is local-only unless explicitly linked to a shared project.
    shared_project_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True)
    shared_server_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)
    shared_project_name: Mapped[Optional[str]] = mapped_column(String(200), nullable=True)
    last_refreshed_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow, onupdate=utcnow)

    sessions: Mapped[list["Session"]] = relationship(back_populates="project", cascade="all, delete-orphan", passive_deletes=True)


class Session(Base):
    __tablename__ = "sessions"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    title: Mapped[str] = mapped_column(String(300), nullable=False)
    purpose: Mapped[str] = mapped_column(Text, default="")
    # active | paused | ended | interrupted (process died while active; recovered on launch)
    state: Mapped[str] = mapped_column(String(20), default="active", index=True)
    started_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    ended_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)
    last_heartbeat_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)
    capture_target: Mapped[str] = mapped_column(String(300), default="foreground")
    transcription_mode: Mapped[str] = mapped_column(String(20), default="after")  # live | after | off
    ai_enabled: Mapped[bool] = mapped_column(Boolean, default=False)
    always_ask_context: Mapped[bool] = mapped_column(Boolean, default=False)
    # Organisation (AI) processing summary: none | queued | running | done | failed | cancelled
    processing_state: Mapped[str] = mapped_column(String(20), default="none")
    raw_audio_deleted: Mapped[bool] = mapped_column(Boolean, default=False)
    is_demo: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)

    project: Mapped[Project] = relationship(back_populates="sessions")
    sources: Mapped[list["AudioSource"]] = relationship(back_populates="session", cascade="all, delete-orphan", passive_deletes=True)


class SessionPause(Base):
    __tablename__ = "session_pauses"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True)
    start_offset_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    end_offset_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    reason: Mapped[str] = mapped_column(String(40), default="user")  # user | restart


class AudioSource(Base):
    __tablename__ = "audio_sources"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True)
    kind: Mapped[str] = mapped_column(String(20), nullable=False)  # mic | loopback
    device_name: Mapped[str] = mapped_column(String(300), default="")
    label: Mapped[str] = mapped_column(String(100), default="")
    sample_rate: Mapped[int] = mapped_column(Integer, default=0)
    channels: Mapped[int] = mapped_column(Integer, default=0)
    # recording | paused | stopped | error | failed
    state: Mapped[str] = mapped_column(String(20), default="stopped")
    last_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    session: Mapped[Session] = relationship(back_populates="sources")
    __table_args__ = (CheckConstraint("kind in ('mic','loopback')", name="ck_source_kind"),)


class AudioEvent(Base):
    """Interruptions, recoveries and errors per source — never hidden from the timeline."""

    __tablename__ = "audio_events"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    source_id: Mapped[str] = mapped_column(ForeignKey("audio_sources.id", ondelete="CASCADE"), index=True)
    kind: Mapped[str] = mapped_column(String(30))  # started | interrupted | resumed | error | stopped | lost_on_crash
    offset_ms: Mapped[int] = mapped_column(Integer)
    message: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)


class AudioChunk(Base):
    __tablename__ = "audio_chunks"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True)
    source_id: Mapped[str] = mapped_column(ForeignKey("audio_sources.id", ondelete="CASCADE"), index=True)
    seq: Mapped[int] = mapped_column(Integer)
    rel_path: Mapped[str] = mapped_column(String(500))  # relative to data_dir/audio
    start_offset_ms: Mapped[int] = mapped_column(Integer)
    duration_ms: Mapped[int] = mapped_column(Integer, default=0)
    sample_rate: Mapped[int] = mapped_column(Integer)
    channels: Mapped[int] = mapped_column(Integer)
    # recording | complete | recovered | missing | deleted
    state: Mapped[str] = mapped_column(String(20), default="recording")
    peak: Mapped[float] = mapped_column(Float, default=0.0)
    contiguous_with_prev: Mapped[bool] = mapped_column(Boolean, default=False)
    __table_args__ = (UniqueConstraint("source_id", "seq", name="uq_chunk_seq"),)


class TranscriptionJob(Base):
    __tablename__ = "transcription_jobs"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True)
    chunk_id: Mapped[str] = mapped_column(ForeignKey("audio_chunks.id", ondelete="CASCADE"), unique=True)
    state: Mapped[str] = mapped_column(String(20), default="queued", index=True)  # queued|running|done|failed
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    model: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    speech_found: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow, onupdate=utcnow)


class TranscriptSegment(Base):
    __tablename__ = "transcript_segments"
    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True)
    source_id: Mapped[str] = mapped_column(ForeignKey("audio_sources.id", ondelete="CASCADE"))
    chunk_id: Mapped[Optional[str]] = mapped_column(ForeignKey("audio_chunks.id", ondelete="SET NULL"), nullable=True)
    start_ms: Mapped[int] = mapped_column(Integer, index=True)
    end_ms: Mapped[int] = mapped_column(Integer)
    text: Mapped[str] = mapped_column(Text)  # raw recognised text, never overwritten
    corrected_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    confidence: Mapped[float] = mapped_column(Float, default=0.0)
    low_confidence: Mapped[bool] = mapped_column(Boolean, default=False)
    model: Mapped[str] = mapped_column(String(100), default="")
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)


class Capture(Base):
    __tablename__ = "captures"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[Optional[str]] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True, nullable=True)
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    taken_at: Mapped[datetime] = mapped_column(UTCDateTime)
    offset_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    image_rel_path: Mapped[str] = mapped_column(String(500))  # relative to media dir
    thumb_rel_path: Mapped[str] = mapped_column(String(500))
    sha256: Mapped[str] = mapped_column(String(64))
    width: Mapped[int] = mapped_column(Integer)
    height: Mapped[int] = mapped_column(Integer)
    monitor: Mapped[Any] = mapped_column(JSON, default=dict)
    window_title: Mapped[str] = mapped_column(String(500), default="")
    trigger: Mapped[str] = mapped_column(String(30), default="hotkey")  # hotkey | hotkey_context | api | demo
    # saved (has note or audio context) | marker (audio on, awaiting transcript) | unfinished | discarded
    status: Mapped[str] = mapped_column(String(20), default="unfinished", index=True)
    needs_context: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)


class Note(Base):
    __tablename__ = "notes"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[Optional[str]] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True, nullable=True)
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    capture_id: Mapped[Optional[str]] = mapped_column(ForeignKey("captures.id", ondelete="SET NULL"), nullable=True)
    text: Mapped[str] = mapped_column(Text)
    category: Mapped[Optional[str]] = mapped_column(String(30), nullable=True)
    kind: Mapped[str] = mapped_column(String(20), default="typed")  # typed | quick | manual
    taken_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    offset_ms: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)


class ProcessingRun(Base):
    __tablename__ = "processing_runs"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True)
    state: Mapped[str] = mapped_column(String(20), default="queued")  # queued|running|done|failed|cancelled
    provider: Mapped[str] = mapped_column(String(40), default="ollama")
    model: Mapped[str] = mapped_column(String(100), default="")
    prompt_version: Mapped[str] = mapped_column(String(40), default="")
    input_fingerprint: Mapped[str] = mapped_column(String(64), default="")
    progress: Mapped[float] = mapped_column(Float, default=0.0)
    stage: Mapped[str] = mapped_column(String(200), default="")
    error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    stats: Mapped[Any] = mapped_column(JSON, default=dict)
    cancel_requested: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    finished_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)


class WorkItem(Base):
    """Canonical approved item. One row per real issue/task."""

    __tablename__ = "work_items"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    session_id: Mapped[Optional[str]] = mapped_column(ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True, index=True)
    type: Mapped[str] = mapped_column(String(20), default="note")
    title: Mapped[str] = mapped_column(String(300))
    description: Mapped[str] = mapped_column(Text, default="")
    work_status: Mapped[str] = mapped_column(String(20), default="open", index=True)
    assignee: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    priority: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    tags: Mapped[Any] = mapped_column(JSON, default=list)
    version: Mapped[int] = mapped_column(Integer, default=1)
    origin: Mapped[str] = mapped_column(String(20), default="local")  # local | shared (pulled from server)
    created_by: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    updated_by: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)
    # Sharing state is independent of review/work status.
    sharing_state: Mapped[str] = mapped_column(String(20), default="local_only", index=True)
    server_version: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    shared_attachment_ids: Mapped[Any] = mapped_column(JSON, default=list)  # capture ids elected for sharing
    shared_excerpts: Mapped[bool] = mapped_column(Boolean, default=False)
    sync_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    conflict_server_copy: Mapped[Any] = mapped_column(JSON, nullable=True)
    last_synced_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)
    completed_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow, onupdate=utcnow)


class DraftItem(Base):
    """A review card. Approving creates/updates exactly one WorkItem."""

    __tablename__ = "draft_items"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    session_id: Mapped[Optional[str]] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), nullable=True, index=True)
    origin: Mapped[str] = mapped_column(String(20), default="typed")  # typed | quick | ai | manual | transcript | split | merge | demo
    type: Mapped[str] = mapped_column(String(20), default="note")
    title: Mapped[str] = mapped_column(String(300))
    description: Mapped[str] = mapped_column(Text, default="")
    review_state: Mapped[str] = mapped_column(String(20), default="pending", index=True)
    needs_context: Mapped[bool] = mapped_column(Boolean, default=False)
    uncertainty: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # From extraction: observation | idea | plan | completed | withdrawn
    statement_kind: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    withdrawn: Mapped[bool] = mapped_column(Boolean, default=False)
    possibly_completed: Mapped[bool] = mapped_column(Boolean, default=False)
    conflict_note: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    human_edited: Mapped[bool] = mapped_column(Boolean, default=False)
    source_fingerprint: Mapped[Optional[str]] = mapped_column(String(64), nullable=True, index=True)
    processing_run_id: Mapped[Optional[str]] = mapped_column(ForeignKey("processing_runs.id", ondelete="SET NULL"), nullable=True)
    work_item_id: Mapped[Optional[str]] = mapped_column(ForeignKey("work_items.id", ondelete="SET NULL"), nullable=True)
    merged_into_id: Mapped[Optional[str]] = mapped_column(ForeignKey("draft_items.id", ondelete="SET NULL"), nullable=True)
    dismissed_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)
    version: Mapped[int] = mapped_column(Integer, default=1)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow, onupdate=utcnow)


class EvidenceLink(Base):
    """Links a card or work item to a capture, transcript segment or note."""

    __tablename__ = "evidence_links"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    draft_id: Mapped[Optional[str]] = mapped_column(ForeignKey("draft_items.id", ondelete="CASCADE"), nullable=True, index=True)
    work_item_id: Mapped[Optional[str]] = mapped_column(ForeignKey("work_items.id", ondelete="CASCADE"), nullable=True, index=True)
    capture_id: Mapped[Optional[str]] = mapped_column(ForeignKey("captures.id", ondelete="CASCADE"), nullable=True, index=True)
    segment_id: Mapped[Optional[str]] = mapped_column(ForeignKey("transcript_segments.id", ondelete="CASCADE"), nullable=True, index=True)
    note_id: Mapped[Optional[str]] = mapped_column(ForeignKey("notes.id", ondelete="CASCADE"), nullable=True, index=True)
    # direct: explicitly attached (typed note, user) | candidate: time-window association | uncertain: overlaps several
    confidence: Mapped[str] = mapped_column(String(20), default="direct")
    role: Mapped[str] = mapped_column(String(20), default="source")  # source | withdrawal | correction | completion | context
    attached_by: Mapped[str] = mapped_column(String(20), default="system")  # system | ai | user
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    __table_args__ = (
        CheckConstraint("(draft_id IS NOT NULL) OR (work_item_id IS NOT NULL)", name="ck_evidence_owner"),
        CheckConstraint(
            "(capture_id IS NOT NULL) + (segment_id IS NOT NULL) + (note_id IS NOT NULL) = 1",
            name="ck_evidence_single_source",
        ),
    )


class ChecklistEntry(Base):
    __tablename__ = "checklist_entries"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    session_id: Mapped[str] = mapped_column(ForeignKey("sessions.id", ondelete="CASCADE"), index=True)
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"))
    text: Mapped[str] = mapped_column(Text)
    work_item_id: Mapped[Optional[str]] = mapped_column(ForeignKey("work_items.id", ondelete="SET NULL"), nullable=True)
    origin: Mapped[str] = mapped_column(String(20), default="planned")  # planned | during | brought_in
    state: Mapped[str] = mapped_column(String(20), default="open")  # open | done | outstanding
    suggested_done: Mapped[bool] = mapped_column(Boolean, default=False)
    suggestion_segment_ids: Mapped[Any] = mapped_column(JSON, default=list)
    position: Mapped[int] = mapped_column(Integer, default=0)
    completed_at: Mapped[Optional[datetime]] = mapped_column(UTCDateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)


class SyncJob(Base):
    """Persistent outbox for publishing to the shared server."""

    __tablename__ = "sync_jobs"
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_id)
    work_item_id: Mapped[str] = mapped_column(ForeignKey("work_items.id", ondelete="CASCADE"), index=True)
    op: Mapped[str] = mapped_column(String(20), default="upsert")
    state: Mapped[str] = mapped_column(String(20), default="pending", index=True)  # pending|done|failed|conflict|cancelled
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    next_attempt_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    last_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow, onupdate=utcnow)


Index("ix_draft_session_state", DraftItem.session_id, DraftItem.review_state)
Index("ix_segments_session_time", TranscriptSegment.session_id, TranscriptSegment.start_ms)
Index("ix_captures_session_time", Capture.session_id, Capture.offset_ms)
