"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 16:58:32.347455
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('glossary', sa.Text(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('shared_project_id', sa.String(length=36), nullable=True),
    sa.Column('shared_server_url', sa.String(length=500), nullable=True),
    sa.Column('shared_project_name', sa.String(length=200), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('capture_target', sa.String(length=300), nullable=False),
    sa.Column('transcription_mode', sa.String(length=20), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('always_ask_context', sa.Boolean(), nullable=False),
    sa.Column('processing_state', sa.String(length=20), nullable=False),
    sa.Column('raw_audio_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_state'), ['state'], unique=False)

    op.create_table('audio_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('device_name', sa.String(length=300), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("kind in ('mic','loopback')", name='ck_source_kind'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_sources_session_id'), ['session_id'], unique=False)

    op.create_table('captures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=True),
    sa.Column('image_rel_path', sa.String(length=500), nullable=False),
    sa.Column('thumb_rel_path', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('monitor', sa.JSON(), nullable=False),
    sa.Column('window_title', sa.String(length=500), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('needs_context', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captures_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_captures_session_time', ['session_id', 'offset_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_captures_status'), ['status'], unique=False)

    op.create_table('processing_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=200), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_runs_session_id'), ['session_id'], unique=False)

    op.create_table('session_pauses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('start_offset_ms', sa.Integer(), nullable=False),
    sa.Column('end_offset_ms', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_pauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_pauses_session_id'), ['session_id'], unique=False)

    op.create_table('work_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('work_status', sa.String(length=20), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('sharing_state', sa.String(length=20), nullable=False),
    sa.Column('server_version', sa.Integer(), nullable=True),
    sa.Column('shared_attachment_ids', sa.JSON(), nullable=False),
    sa.Column('shared_excerpts', sa.Boolean(), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('conflict_server_copy', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_items_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_sharing_state'), ['sharing_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_work_status'), ['work_status'], unique=False)

    op.create_table('audio_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('rel_path', sa.String(length=500), nullable=False),
    sa.Column('start_offset_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('peak', sa.Float(), nullable=False),
    sa.Column('contiguous_with_prev', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['audio_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'seq', name='uq_chunk_seq')
    )
    with op.batch_alter_table('audio_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_chunks_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_chunks_source_id'), ['source_id'], unique=False)

    op.create_table('audio_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['audio_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_events_source_id'), ['source_id'], unique=False)

    op.create_table('checklist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('suggested_done', sa.Boolean(), nullable=False),
    sa.Column('suggestion_segment_ids', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_entries_session_id'), ['session_id'], unique=False)

    op.create_table('draft_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('review_state', sa.String(length=20), nullable=False),
    sa.Column('needs_context', sa.Boolean(), nullable=False),
    sa.Column('uncertainty', sa.Text(), nullable=True),
    sa.Column('statement_kind', sa.String(length=20), nullable=True),
    sa.Column('withdrawn', sa.Boolean(), nullable=False),
    sa.Column('possibly_completed', sa.Boolean(), nullable=False),
    sa.Column('conflict_note', sa.Text(), nullable=True),
    sa.Column('human_edited', sa.Boolean(), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('processing_run_id', sa.String(length=36), nullable=True),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('merged_into_id', sa.String(length=36), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['draft_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_items_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_items_review_state'), ['review_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_items_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_items_source_fingerprint'), ['source_fingerprint'], unique=False)
        batch_op.create_index('ix_draft_session_state', ['session_id', 'review_state'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('capture_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('offset_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_session_id'), ['session_id'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('op', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['audio_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['audio_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_session_time', ['session_id', 'start_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_segments_start_ms'), ['start_ms'], unique=False)

    op.create_table('transcription_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('speech_found', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['audio_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id')
    )
    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcription_jobs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcription_jobs_state'), ['state'], unique=False)

    op.create_table('evidence_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=True),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('capture_id', sa.String(length=36), nullable=True),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('note_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('attached_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(capture_id IS NOT NULL) + (segment_id IS NOT NULL) + (note_id IS NOT NULL) = 1', name='ck_evidence_single_source'),
    sa.CheckConstraint('(draft_id IS NOT NULL) OR (work_item_id IS NOT NULL)', name='ck_evidence_owner'),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_links_capture_id'), ['capture_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_links_work_item_id'), ['work_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_links_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_segment_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_note_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_draft_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_links_capture_id'))

    op.drop_table('evidence_links')
    with op.batch_alter_table('transcription_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcription_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_transcription_jobs_session_id'))

    op.drop_table('transcription_jobs')
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcript_segments_start_ms'))
        batch_op.drop_index(batch_op.f('ix_transcript_segments_session_id'))
        batch_op.drop_index('ix_segments_session_time')

    op.drop_table('transcript_segments')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_state'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_session_id'))
        batch_op.drop_index(batch_op.f('ix_notes_project_id'))

    op.drop_table('notes')
    with op.batch_alter_table('draft_items', schema=None) as batch_op:
        batch_op.drop_index('ix_draft_session_state')
        batch_op.drop_index(batch_op.f('ix_draft_items_source_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_draft_items_session_id'))
        batch_op.drop_index(batch_op.f('ix_draft_items_review_state'))
        batch_op.drop_index(batch_op.f('ix_draft_items_project_id'))

    op.drop_table('draft_items')
    with op.batch_alter_table('checklist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_entries_session_id'))

    op.drop_table('checklist_entries')
    with op.batch_alter_table('audio_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_events_source_id'))

    op.drop_table('audio_events')
    with op.batch_alter_table('audio_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_chunks_source_id'))
        batch_op.drop_index(batch_op.f('ix_audio_chunks_session_id'))

    op.drop_table('audio_chunks')
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_work_status'))
        batch_op.drop_index(batch_op.f('ix_work_items_sharing_state'))
        batch_op.drop_index(batch_op.f('ix_work_items_session_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_project_id'))

    op.drop_table('work_items')
    with op.batch_alter_table('session_pauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_pauses_session_id'))

    op.drop_table('session_pauses')
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_runs_session_id'))

    op.drop_table('processing_runs')
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captures_status'))
        batch_op.drop_index('ix_captures_session_time')
        batch_op.drop_index(batch_op.f('ix_captures_session_id'))
        batch_op.drop_index(batch_op.f('ix_captures_project_id'))

    op.drop_table('captures')
    with op.batch_alter_table('audio_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_sources_session_id'))

    op.drop_table('audio_sources')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_state'))
        batch_op.drop_index(batch_op.f('ix_sessions_project_id'))

    op.drop_table('sessions')
    op.drop_table('settings')
    op.drop_table('projects')
    # ### end Alembic commands ###
