"""handoffs

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 19:12:29.204347
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handoffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('item_ids', sa.JSON(), nullable=False),
    sa.Column('include_screenshots', sa.Boolean(), nullable=False),
    sa.Column('include_excerpts', sa.Boolean(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handoffs')
    # ### end Alembic commands ###
